### ISSUE TITLE
ts_library does not copy user declare typings file

### ISSUE THREAD

**Issue by sandangel** [bazelbuild/rules_typescript#197] opened 2018-05-05 13:20 UTC
when import type from a declaration .d.ts file, .d.ts file is not copied to the built destination which breaks `npm_package` rule.

for example, I'm building an angular/schematics lib which has schema declared in schema.d.ts file. After built with ts_library, index.ts file will produce index.d.ts: `import {Schema} from './schema'` => lib depend on schema.d.ts, but since the schema.d.ts was missing in the built destination, the npm_package rule will fail.

```
ts_library(
    name = "schematics",
    srcs = glob(
        [
            "**/*.ts", # including schema.d.ts
        ],
        exclude = [
            "**/test/**/*.ts",
            "**/*_spec.ts",
        ],
    ),
    tsconfig = "//projects/schematics:tsconfig-build.json",
)

npm_package(
    name = "npm_package",
    srcs = [
        "package.json",
        "collection.json",
        "action_helper/schema.json",
    ],
    tags = ["publish"],
    deps = [
        ":schematics",
    ],
)
``` 

```
ERROR: /Users/sand/Downloads/ng6/projects/schematics/BUILD.bazel:31:1: SkylarkAction projects/schematics/npm_package failed (Exit 1)
failed to load main  Error: dependency projects/schematics/action_helper/schema.d.ts is not under bazel-bin or bazel-genfiles
    at outPath (/private/var/tmp/_bazel_sand/09cd38cf0582a63d96f315031092ac4d/external/build_bazel_rules_nodejs/internal/npm_package/packager.js:84:13)
    at main (/private/var/tmp/_bazel_sand/09cd38cf0582a63d96f315031092ac4d/external/build_bazel_rules_nodejs/internal/npm_package/packager.js:92:11)
    at Object.<anonymous> (/private/var/tmp/_bazel_sand/09cd38cf0582a63d96f315031092ac4d/external/build_bazel_rules_nodejs/internal/npm_package/packager.js:122:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Object.<anonymous> (/private/var/tmp/_bazel_sand/09cd38cf0582a63d96f315031092ac4d/execroot/ngrx_utils/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager_bin_loader.js:290:24)
    at Module._compile (module.js:635:30)
Target //projects/schematics:npm_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.456s, Critical Path: 4.55s
INFO: 6 processes: 3 darwin-sandbox, 3 local.
FAILED: Build did NOT complete successfully
```

**Comment by alexeagle** [comment] 2018-05-10 00:45
looks like a duplicate of https://github.com/bazelbuild/rules_nodejs/issues/196 which I just fixed yesterday. Next release will have the fix (or you can point your WORKSPACE to the sha1 of HEAD for your rules_nodejs)

**Closed by alexeagle** 2018-05-10 00:45 UTC
