### ISSUE TITLE
ERROR: Failed to load Skylark extension '@bazel_skylib//:lib.bzl'.

### ISSUE THREAD

**Issue by oferb** [bazelbuild/rules_typescript#233] opened 2018-07-23 20:34 UTC
I'm getting the following error:
```
ERROR: Failed to load Skylark extension '@bazel_skylib//:lib.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository 'bazel_skylib' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing
```
It disappears when I remove the following from `WORKSPACE`:
`load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")`
`ts_setup_workspace()`
That's why I'm opening this issue here.

Another odd thing, is that it worked, until I did `bazel clean --expunge` and then it started giving the error.

Steps to reproduce (done on Linux):
1. `git clone https://github.com/google/startup-os`
2. `bazel build //common:all` (though any build seems to give the error)

Thanks!

**Comment by alexeagle** [comment] 2018-07-23 22:41
Duplicate of https://github.com/bazelbuild/rules_typescript/issues/202

We should have noted the breaking change. I think this was introduced when we added a dependency on rules_webtesting. https://github.com/bazelbuild/rules_webtesting/commit/7a29649bbad874b72081d5bac36a91523ce50269
Their README also fails to indicate that users need this dependency.

**Closed by alexeagle** 2018-07-23 22:41 UTC

**Comment by oferb** [comment] 2018-07-24 07:46
Thanks!
This commit fixes the issue: https://github.com/google/startup-os/pull/196/commits/f911766a4cd70d60999c63fa39b1b14dc5cd810f

One thing I've noticed through this though, is that depending on `master` makes bazel builds non-reproducible, as in this example where it was working until I did `bazel clean --expunge` which made it stop working (probably due to getting the latest `master`).

**Comment by alexeagle** [comment] 2018-07-24 13:39
right, you should never have floating dependencies - always make sure your
dependencies are locked so that breakages occur only when you make a change.

**Comment by kellycampbell** [comment] 2018-07-27 14:52
We have one developer running into this problem, but we don't know why yet. We're are pinned to a specific commit in our WORKSPACE:

```
git_repository(
    name = "build_bazel_rules_typescript",
    remote = "https://github.com/bazelbuild/rules_typescript.git",
    commit = "3f3bf6df35c890733350bbc27d98a7174340c3d0", # rel: 0.15.1
)
```

**Comment by kellycampbell** [comment] 2018-07-27 15:00
We think we figured it out. Our rules_webtesting dependency points to their master because that's what their README has as the examples.
